#! /usr/env/python

import os
import psutil

MEGA = 10 ** 6
MEGA_STR = ' ' * MEGA

def pmem():
    tot, avail, percent, used, free, active, inactive, buffer, cached = psutil.virtual_memory()
    tot, avail, used, free , active, inactive, buffer, cached = tot / MEGA, avail / MEGA, used / MEGA, free / MEGA , active / MEGA ,inactive / MEGA, buffer / MEGA, cached / MEGA
    print('total = %s avail = %s used = %s free = %s percent = %s active = %s inactive = %s buffer = %s cached = %s'
          % (tot, avail, used, free, percent, active, inactive, buffer, cached))

a = []
while True:
    pmem()
    print ('String length (* 10^6) = %s ' % len(a))
    a.append(' ' * MEGA)
